from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from .errors import AbhError
from .storage import root_dir, write_text


HOOK_PROFILE_NAME = "default"
HOOK_NAME = "pre-commit"
HOOK_PATH = ".git/hooks/pre-commit"
MANAGED_MARKER = "ABH MANAGED PRE-COMMIT"
DEFAULT_COMMANDS = (
    "python3 -m abh doctor",
    "python3 -m abh roadmap check --json",
    "git diff --check",
)
DEFAULT_INVARIANTS = (
    "plan_doc_sync",
    "roadmap_queue_consistency",
    "whitespace_clean_diff",
)


@dataclass(frozen=True, slots=True)
class HookAction:
    path: str
    kind: str
    reason: str

    def to_dict(self) -> dict[str, str]:
        return {"path": self.path, "kind": self.kind, "reason": self.reason}


def hook_profile() -> dict[str, object]:
    return {
        "name": HOOK_PROFILE_NAME,
        "hook": HOOK_NAME,
        "path": HOOK_PATH,
        "managed_marker": MANAGED_MARKER,
        "commands": list(DEFAULT_COMMANDS),
        "invariants": list(DEFAULT_INVARIANTS),
        "write_policy": {
            "mode": "preview_by_default",
            "requires": ["--write", "--confirm"],
            "overwrite": "managed_abh_hooks_only",
        },
    }


def _hook_content() -> str:
    commands = "\n".join(DEFAULT_COMMANDS)
    return (
        "#!/bin/sh\n"
        f"# {MANAGED_MARKER}\n"
        "# Generated by `abh hooks install`; rerun that command to refresh this file.\n\n"
        "set -eu\n\n"
        f"{commands}\n"
    )


def preview_hook_install(*, cwd: Path | None = None, write: bool = False, confirmed: bool = False) -> dict[str, object]:
    root = root_dir(cwd)
    hook_path = root / HOOK_PATH
    writes: list[HookAction] = []
    skips: list[HookAction] = []
    blockers: list[HookAction] = []

    if hook_path.exists():
        content = hook_path.read_text(encoding="utf-8")
        if MANAGED_MARKER in content:
            writes.append(HookAction(path=HOOK_PATH, kind="file", reason="refresh managed ABH hook"))
        else:
            blockers.append(HookAction(path=HOOK_PATH, kind="file", reason="existing unmanaged hook; will not overwrite"))
    else:
        writes.append(HookAction(path=HOOK_PATH, kind="file", reason="install managed ABH pre-commit guardrail hook"))

    return {
        "mode": "write" if write else "preview",
        "write": write,
        "confirmed": confirmed,
        "profile": hook_profile(),
        "path": HOOK_PATH,
        "writes": [action.to_dict() for action in writes],
        "skips": [action.to_dict() for action in skips],
        "blockers": [action.to_dict() for action in blockers],
    }


def install_hooks(*, cwd: Path | None = None, write: bool = False, confirmed: bool = False) -> dict[str, object]:
    if write and not confirmed:
        raise AbhError("abh hooks install --write requires --confirm")

    root = root_dir(cwd)
    result = preview_hook_install(cwd=root, write=write, confirmed=confirmed)
    blockers = result["blockers"]
    if blockers and write:
        raise AbhError("existing unmanaged hook at .git/hooks/pre-commit; will not overwrite")
    if not write:
        return result

    hook_path = root / HOOK_PATH
    write_text(hook_path, _hook_content())
    current_mode = hook_path.stat().st_mode
    hook_path.chmod(current_mode | 0o111)
    return result
